### ISSUE TITLE
repo accidentally deleted

### ISSUE THREAD

**Issue by parro-it** [parro-it/awesome-micro-npm-packages#1]
Aaargh! I accidentally deleted this repo while submitting it to [awesome](https://github.com/sindresorhus/awesome).
Fortunately, I saved a copy of the list on my dev machine...
I will rewrite all other files, but commit history, stars and watchers are definitely lost :cry: 
So sorry with all the watchers...

**Comment by jonschlinkert** [comment]
sorry to hear that! glad you got it worked out!

**Comment by parro-it** [comment]
Thank you @jonschlinkert. It was a big DOH! moment :smile:

**Comment by jonschlinkert** [comment]
it's a nice reference, it will get back up to speed in no time! thanks for creating it.

**Comment by parro-it** [comment]
Glad you appreciate it, I'm also finding it useful because I often forget which modules I've already used in past. Now I can find theme here...
Feel free to contribute with your modules if you want!

**Comment by jonschlinkert** [comment]
great, thanks!
