### ISSUE TITLE
Adding `Utils / Utilities` section?

### ISSUE THREAD

**Issue by tunnckoCore** [parro-it/awesome-micro-npm-packages#14]
I see the `Other` section, but I don't think utils are exactly "Other" thing.

**Comment by parro-it** [comment]
If what do means by utils it's tools like babel, browserify etc. then I prefer to avoid them thanks. I want to include only libraries here.
Otherwise, could you do some example of util libs?

**Comment by parro-it** [comment]
Closing for lack of response

**Comment by tunnckoCore** [comment]
Damn, I completely forgot that, sorry.

> If what do means by utils it's tools like babel, browserify etc.

No. Things like `is-arguments`, `is-async-function`, `is-emitter`, `is-stream`, `is-child-process`, `is-callback-function`, `is-plural/singular` and etc.

**Comment by parro-it** [comment]
No worries @tunnckoCore! There is already some is-\* on the list. 

I initially thought to create a `predicates` section, but then I've chosen to try put every predicate module in its category, where applicable. E.g. `is-arguments`, `is-async-function,`is-callback-function`could fit in`function`category,`is-stream` in stream category etc.

**Comment by tunnckoCore** [comment]
Yea, same here, maybe because of that I didn't answer in shorter time. But yea, what you choose. :)
