### ISSUE TITLE
minor re-organization to alphabetical order? 

### ISSUE THREAD

**Issue by jonschlinkert** [parro-it/awesome-micro-npm-packages#40]
Would you be opposed to re-organizing the sections and lists by alphabetical order? As the list grows it will be easier to scan for information. 

I'd be happy to do a PR

**Comment by parro-it** [comment]
> Would you be opposed to re-organizing the sections and lists by alphabetical order? As the list grows it will be easier to scan for information.

Not at all, I think it could be useful. 

> I'd be happy to do a PR

🍾  that's great! thank you...

**Comment by jonschlinkert** [comment]
How about a TOC?

**Comment by parro-it** [comment]
Oh yes, good idea too... Will you use some tool for this? 
I guess you wrote some good one 😄

**Comment by jonschlinkert** [comment]
Lol, I was going to do it by hand. But we can use `markdown-toc` if you want. 

The command would be:

```sh
$ markdown-toc readme.md
```

and that would just update the TOC. Any preference?

**Comment by jonschlinkert** [comment]
Great, one more question... How about some new sections, for buffer, error, regular expressions, and other native types that are missing? Or we can just keep it as-is for now.

edit: then we can rename that section to "JavaScript Native Types" or something. thoughts?

edit 2: should I sort "Small modules rockstars to follow" by first name, last name, or GitHub username?

**Comment by parro-it** [comment]
> buffer, error, regular expressions

That's ok

> other native types

There's already a "string" and a "math" section (for numbers). There's still Boolean, I would prefer a "Logic section" only for that... 

Or did I misunderstand what you mean by "native types"?

**Comment by parro-it** [comment]
By the way, I'm also thinking of adding a "Collections" section containing
modules developed around the same theme. 

It will, by now, contains https://github.com/sindresorhus/promise-fun by Sindre Sorhus and https://github.com/parro-it/ai-fun by me (not completed yet, inspired by the former).

Do you think it could be a useful section?

**Comment by jonschlinkert** [comment]
> Or did I misunderstand what you mean by "native types"?

Maybe, I just meant all of the native javascript types (primitives and object types. for example, `Number` is a primitive, `Math` is a global object for mathematical operations). But to your point, maybe there is little use for a number section if math isn't involved. 

For now I'll just do the TOC and sorting, and we can go from there. 


> Do you think it could be a useful section?

Hmm, might be beyond the scope of this lib IMHO.
