### ISSUE TITLE
node-uuid package is wrong (deprecated)

### ISSUE THREAD

**Issue by ugo-buonadonna** [parro-it/awesome-micro-npm-packages#41]
Hi,

the `node-uuid` package is now just `uuid`, as you can see [here](https://www.npmjs.com/package/node-uuid).

I think it's better to just call id `uuid` to avoid people mistakenly installing the deprecated `node-uuid`. Does this make sense?

Anyway, good job!

**Comment by parro-it** [comment]
You're right, thank you!
I was thinking the same yesterday but didn't get the time to correct... 
Would you mind doing a PR? 🙏🏻
