### ISSUE TITLE
Add package size to each line

### ISSUE THREAD

**Issue by styfle** [parro-it/awesome-micro-npm-packages#52]
I would like to suggest adding the package size to each line.

It could just simply be a badge that gets the size in real time, see [Package Phobia](https://packagephobia.now.sh).

For example:

- [is-sorted](https://github.com/dcousens/is-sorted) [![install size](https://packagephobia.now.sh/badge?p=is-sorted@1.0.4)](https://packagephobia.now.sh/result?p=is-sorted@1.0.4) - A small module to check if an Array is sorted.
- [array-first](https://github.com/jonschlinkert/array-first) [![install size](https://packagephobia.now.sh/badge?p=array-first@1.0.2)](https://packagephobia.now.sh/result?p=array-first@1.0.2) - Get the first element or first n elements of an array.

@parro-it Thoughts?

**Comment by parro-it** [comment]
Yes, it could be interesting, but it will complicate adding new entries to the list, while I want to keep that process really simple: every time I found an interesting micro-package, I quickly add it here.

**Comment by styfle** [comment]
It will not complicate it, I've already done all the work to calculate the size.

You just add a link to the image like so:

```
https://packagephobia.now.sh/badge?p=is-sorted
https://packagephobia.now.sh/badge?p=array-first
```

**Comment by styfle** [comment]
Read more here: https://github.com/styfle/packagephobia

**Comment by michaelzoidl** [comment]
@styfle, i think there is a problem behind your idea, you're measure the size of the _package_ but at the end of the day i want to know how big is the size of the file is i will include in my project, if you're using badgesize and jsdelivr you can figure out this information:
- [is-sorted](https://github.com/dcousens/is-sorted) ![](http://img.badgesize.io/https://cdn.jsdelivr.net/npm/is-sorted/index.js)
> `http://img.badgesize.io/https://cdn.jsdelivr.net/npm/is-sorted/index.js`
- [array-first](https://github.com/jonschlinkert/array-first) ![](http://img.badgesize.io/https://cdn.jsdelivr.net/npm/array-first/index.js)
> `http://img.badgesize.io/https://cdn.jsdelivr.net/npm/array-first/index.js`

With this way you will also only measuring the files in the npm package - if you're using some kind of a minifier in your project you will reduce the size anyway.

But i like the idea to show a information like that in a repo, if its making the list confusing has @parro-it to decide.

**Comment by styfle** [comment]
@michaelzoidl Yea I agree with you if we’re talking about packages that run in the browser (there is actually a Broswer section in the readme). However, Package Phobia exists because many packages do not run in the browser (see the File System section of the readme).
