### ISSUE TITLE
Discuss lagden-promisify & thenify

### ISSUE THREAD

**Issue by Siilwyn** [parro-it/awesome-micro-npm-packages#7]
I think [`lagden-promisify`](https://github.com/lagden/promisify) is a good addition to the list under the 'Promise' section. It doesn't depend on a Promise library like `thenify` does thus it's more lightweight. Should I add it besides `thenify` or replace `thenify`?

If added besides `thenify` I think the description should be clear about the difference between the two. Thoughts?

**Comment by parro-it** [comment]
While I agree with you on disadvantages of `thenify`, I have some concern about `lagden-promisify`. Not on the module itself, (it appear to be well-crafted) but it is really young, the repo on GH has no issue and no stars, and there is only one dependent on npm.

Why not [pify](https://github.com/sindresorhus/pify) instead? It has lot of dependents, a decent number of stars on GH, and it has same pros of `lagden-promisify`. As a bonus, it work also with old node version, it just accept a Promise constructor as a option to use if native is not supported. 

If you go with `pify`, feel free to replace `thenify` entry on the list.

**Comment by Siilwyn** [comment]
Didn't know about `pify`, it looks like a better alternative to `thenify` because it takes away the disadvantage while remaining flexible. I still feel like `lagden-promisify` is a really small and simple package that deserves a place in the list even though it's very new.

What about replacing `thenify` with `pify` and adding `lagden-promisify`?

**Comment by parro-it** [comment]
>  I still feel like lagden-promisify is a really small and simple package that deserves a place in the list even though it's very new.

It is for sure, I looked at the repo and it looks good. But I don't want to include modules with overlapped functionalities, and `pify` is a better suggestion at the moment.
